-- =========================
-- DROP TABLES (ignore errors manually)
-- =========================

DROP TABLE answers CASCADE CONSTRAINTS;
DROP TABLE responses CASCADE CONSTRAINTS;
DROP TABLE options CASCADE CONSTRAINTS;
DROP TABLE questions CASCADE CONSTRAINTS;
DROP TABLE forms CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE form_templates CASCADE CONSTRAINTS;
DROP TABLE audit_logs CASCADE CONSTRAINTS;

-- =========================
-- USERS
-- =========================
CREATE TABLE users (
    user_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    email       VARCHAR2(200) UNIQUE NOT NULL,
    password    VARCHAR2(255) NOT NULL,
    user_type   VARCHAR2(20) NOT NULL
        CHECK (LOWER(user_type) IN ('student', 'faculty')),
    department  VARCHAR2(50) NOT NULL,
    batch       NUMBER,
    joined_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- FORMS
-- =========================
CREATE TABLE forms (
    form_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR2(150) NOT NULL,
    description     CLOB,
    creator_id      NUMBER NOT NULL,
    access_type     VARCHAR2(20) NOT NULL
        CHECK (LOWER(access_type) IN ('public', 'group')),
    target_dept     VARCHAR2(50),
    deadline        TIMESTAMP NOT NULL,
    status          VARCHAR2(20) DEFAULT 'open' NOT NULL
        CHECK (LOWER(status) IN ('open', 'closed')),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    form_code       VARCHAR2(20) NOT NULL UNIQUE,
    report_released VARCHAR2(5) DEFAULT 'no'
        CHECK (LOWER(report_released) IN ('yes', 'no')),
    theme_color     VARCHAR2(20) DEFAULT 'emerald',
    allow_multiple  VARCHAR2(5) DEFAULT 'no'
        CHECK (LOWER(allow_multiple) IN ('yes', 'no')),
    CONSTRAINT fk_forms_creator
        FOREIGN KEY (creator_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- =========================
-- AUDIT LOGS
-- =========================
CREATE TABLE audit_logs (
    log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR2(100) NOT NULL,
    user_id     NUMBER,
    form_id     NUMBER,
    log_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_form
        FOREIGN KEY (form_id) REFERENCES forms(form_id) ON DELETE SET NULL
);

-- =========================
-- QUESTIONS
-- =========================
CREATE TABLE questions (
    question_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id         NUMBER NOT NULL,
    question_text   CLOB NOT NULL,
    question_type   VARCHAR2(20) NOT NULL
        CHECK (LOWER(question_type) IN ('text', 'textarea', 'number', 'email', 'date', 'mcq')),
    is_required     NUMBER(1) NOT NULL CHECK (is_required IN (0,1)),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_questions_form
        FOREIGN KEY (form_id)
        REFERENCES forms(form_id)
        ON DELETE CASCADE
);

-- =========================
-- OPTIONS
-- =========================
CREATE TABLE options (
    option_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id NUMBER NOT NULL,
    option_text CLOB NOT NULL,
    CONSTRAINT fk_options_question
        FOREIGN KEY (question_id)
        REFERENCES questions(question_id)
        ON DELETE CASCADE
);

-- =========================
-- RESPONSES
-- =========================
CREATE TABLE responses (
    response_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id     NUMBER NOT NULL,
    user_id     NUMBER NOT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_responses_form
        FOREIGN KEY (form_id)
        REFERENCES forms(form_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_responses_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- =========================
-- ANSWERS
-- =========================
CREATE TABLE answers (
    answer_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id        NUMBER NOT NULL,
    question_id        NUMBER NOT NULL,
    answer_text        CLOB,
    answer_number      NUMBER(10,4),
    selected_option_id NUMBER,
    CONSTRAINT fk_answers_response
        FOREIGN KEY (response_id)
        REFERENCES responses(response_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_answers_question
        FOREIGN KEY (question_id)
        REFERENCES questions(question_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_answers_option
        FOREIGN KEY (selected_option_id)
        REFERENCES options(option_id),
    CONSTRAINT chk_one_answer_only CHECK (
        (answer_text IS NOT NULL AND answer_number IS NULL AND selected_option_id IS NULL)
        OR
        (answer_text IS NULL AND answer_number IS NOT NULL AND selected_option_id IS NULL)
        OR
        (answer_text IS NULL AND answer_number IS NULL AND selected_option_id IS NOT NULL)
    )
);

-- =========================
-- SAMPLE DATA (2 ROWS PER TABLE)
-- =========================

-- USERS
INSERT INTO users (name, email, password, user_type, department, batch) 
VALUES ('Alice Miller', 'alice.miller@college.edu', 'hashedpw123', 'student', 'Computer Science', 2024);

INSERT INTO users (name, email, password, user_type, department) 
VALUES ('Dr. Bob Smith', 'bob.smith@college.edu', 'hashedpw456', 'faculty', 'Computer Science');

-- FORMS
INSERT INTO forms (title, description, creator_id, access_type, deadline, form_code, status)
VALUES ('Midsem Feedback', 'Feedback for Midsem Exams', 2, 'public', SYSTIMESTAMP + INTERVAL '7' DAY, 'FF-1A2B3C', 'open');

INSERT INTO forms (title, description, creator_id, access_type, target_dept, deadline, form_code, status)
VALUES ('CS Dept Survey', 'Departmental survey for CS students', 2, 'group', 'Computer Science', SYSTIMESTAMP + INTERVAL '14' DAY, 'FF-9Z8Y7X', 'open');

-- QUESTIONS
INSERT INTO questions (form_id, question_text, question_type, is_required)
VALUES (1, 'How would you rate the exam difficulty?', 'mcq', 1);

INSERT INTO questions (form_id, question_text, question_type, is_required)
VALUES (1, 'Any additional comments?', 'text', 0);

-- OPTIONS
INSERT INTO options (question_id, option_text) VALUES (1, 'Easy');
INSERT INTO options (question_id, option_text) VALUES (1, 'Medium');

-- RESPONSES
INSERT INTO responses (form_id, user_id) VALUES (1, 1);
INSERT INTO responses (form_id, user_id) VALUES (2, 1);

-- ANSWERS
INSERT INTO answers (response_id, question_id, selected_option_id) VALUES (1, 1, 1);
INSERT INTO answers (response_id, question_id, answer_text) VALUES (1, 2, 'The exam was fair.');


-- =========================
-- PL/SQL PROCEDURES, FUNCTIONS & TRIGGERS
-- =========================

-- 1. TRIGGER: Prevent forms from being created with a past deadline
CREATE OR REPLACE TRIGGER trg_form_deadline_check
BEFORE INSERT OR UPDATE ON forms
FOR EACH ROW
BEGIN
    IF INSERTING OR (UPDATING AND :NEW.deadline != :OLD.deadline) THEN
        IF :NEW.deadline <= SYSTIMESTAMP THEN
            RAISE_APPLICATION_ERROR(-20001, 'Form deadline cannot be in the past.');
        END IF;
    END IF;
END;
/

-- 2. PROCEDURE: Automatically close expired forms
CREATE OR REPLACE PROCEDURE prc_close_expired_forms IS
BEGIN
    UPDATE forms 
    SET status = 'closed'
    WHERE status = 'open' AND deadline < SYSTIMESTAMP;
    
    COMMIT;
END;
/

-- 3. FUNCTION: Get total number of responses for a form
CREATE OR REPLACE FUNCTION fn_get_response_count(p_form_id IN NUMBER) 
RETURN NUMBER IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM responses
    WHERE form_id = p_form_id;
    
    RETURN v_count;
END;
/

-- 4. TRIGGER: Prevent responses on closed or expired forms
CREATE OR REPLACE TRIGGER trg_prevent_invalid_response
BEFORE INSERT ON responses
FOR EACH ROW
DECLARE
    v_status VARCHAR2(20);
    v_deadline TIMESTAMP;
BEGIN
    SELECT status, deadline INTO v_status, v_deadline
    FROM forms 
    WHERE form_id = :NEW.form_id;

    IF v_status = 'closed' OR v_deadline < SYSTIMESTAMP THEN
        RAISE_APPLICATION_ERROR(-20002, 'Cannot submit response: Form is closed or expired.');
    END IF;
END;
/

-- 5. PROCEDURE: Toggle Form Status (Open/Closed)
CREATE OR REPLACE PROCEDURE prc_toggle_form_status(
    p_form_id IN NUMBER,
    p_new_status OUT VARCHAR2
) IS
    v_current_status VARCHAR2(20);
BEGIN
    SELECT status INTO v_current_status
    FROM forms 
    WHERE form_id = p_form_id;

    IF v_current_status = 'open' THEN
        p_new_status := 'closed';
    ELSE
        p_new_status := 'open';
    END IF;

    UPDATE forms 
    SET status = p_new_status 
    WHERE form_id = p_form_id;
    
    COMMIT;
END;
/

-- =========================
-- TEMPLATE ENGINE
-- =========================

-- We use a single modernized table utilizing a JSON CLOB structure, 
-- heavily optimizing DB I/O and making loading instant.
CREATE TABLE form_templates (
    template_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(255),
    structure CLOB NOT NULL
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Event Registration', 
    'A standard form for collecting event attendee details.',
    '[{"text":"Full Name","type":"text","required":true},{"text":"Email Address","type":"text","required":true},{"text":"T-Shirt Size","type":"mcq","required":true,"options":["Small","Medium","Large","XL"]},{"text":"Dietary Restrictions","type":"text","required":false}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Course Evaluation', 
    'End of semester feedback collection.',
    '[{"text":"Rate the course difficulty (1-5)","type":"number","required":true},{"text":"Rate the instructor (1-5)","type":"number","required":true},{"text":"What did you like most about this course?","type":"text","required":false},{"text":"Would you recommend this course?","type":"mcq","required":true,"options":["Yes","No"]}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Faculty Feedback Form', 
    'Detailed anonymous feedback for teaching faculty.',
    '[{"text":"Faculty Name","type":"text","required":true},{"text":"Subject","type":"text","required":true},{"text":"Teaching Quality (1-5)","type":"number","required":true},{"text":"Clarity of Explanation (1-5)","type":"number","required":true},{"text":"Interaction Level (1-5)","type":"number","required":true},{"text":"Additional Comments","type":"text","required":false}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Quiz / Internal Test', 
    'A standard multiple-choice quiz format.',
    '[{"text":"Student Name / Roll No","type":"text","required":true},{"text":"What does DBMS stand for?","type":"mcq","required":true,"options":["Database Management System","Data Base Multi System","Data Backup Management Structure","None of the above"]},{"text":"Which of the following is a DDL command?","type":"mcq","required":true,"options":["INSERT","UPDATE","CREATE","SELECT"]},{"text":"Explain the difference between Primary Key and Unique Key briefly (Optional)","type":"text","required":false}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Leave Application (Student)', 
    'Official leave request for students.',
    '[{"text":"Name / Roll No","type":"text","required":true},{"text":"From Date (DD/MM/YYYY)","type":"text","required":true},{"text":"To Date (DD/MM/YYYY)","type":"text","required":true},{"text":"Type of Leave","type":"mcq","required":true,"options":["Medical","Personal","Other"]},{"text":"Detailed Reason","type":"text","required":true}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Lab Feedback Form', 
    'Feedback collection for laboratory sessions.',
    '[{"text":"Lab Name / Course Code","type":"text","required":true},{"text":"Equipment Quality (1-5)","type":"number","required":true},{"text":"Lab Instructor Helpfulness (1-5)","type":"number","required":true},{"text":"Overall Difficulty Level","type":"mcq","required":true,"options":["Easy","Medium","Hard"]},{"text":"Any specific suggestions?","type":"text","required":false}]'
);

INSERT INTO form_templates (name, description, structure) VALUES (
    'Doubt/Query Submission', 
    'Direct question submission to faculty.',
    '[{"text":"Full Name","type":"text","required":true},{"text":"Subject / Topic","type":"text","required":true},{"text":"What is your question?","type":"text","required":true},{"text":"Priority Level","type":"mcq","required":false,"options":["High","Medium","Low"]}]'
);

-- 6. TRIGGER: Audit Form Creation
CREATE OR REPLACE TRIGGER trg_audit_form_creation
AFTER INSERT ON forms
FOR EACH ROW
BEGIN
    INSERT INTO audit_logs (action_type, user_id, form_id)
    VALUES ('CREATED NEW FORM', :NEW.creator_id, :NEW.form_id);
END;
/

-- 7. TRIGGER: Audit Response Submission
CREATE OR REPLACE TRIGGER trg_audit_response
AFTER INSERT ON responses
FOR EACH ROW
BEGIN
    INSERT INTO audit_logs (action_type, user_id, form_id)
    VALUES ('SUBMITTED RESPONSE', :NEW.user_id, :NEW.form_id);
END;
/